services:
  php:
    image: abourtnik/laravel
    container_name: php_container
    working_dir: /var/www/html
    volumes:
        - ./:/var/www/html
        - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
        - application
    depends_on:
        - mariadb
    restart: unless-stopped
  nginx:
      image: nginx:1.22.0-alpine
      container_name: nginx_container
      networks:
          - application
      ports:
          - "8080:80"
      volumes:
          - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./:/var/www/html
      links:
          - php
      restart: unless-stopped
  typesense:
    image: typesense/typesense:28.0
    container_name: typesense_container
    volumes:
      - ./docker/data/typesense:/data
    ports:
        - "8108:8108"
    restart: on-failure
    networks:
        - application
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'
  mariadb:
    image: mariadb:11.6.2
    container_name: mariadb_container
    ports:
        - "3306:3306"
    environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          TZ: 'Europe/Paris'
    volumes:
      - ./docker/data/mariadb:/var/lib/mysql
      - ./database/dumps:/dumps
    networks:
      - application
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: root
    links:
      - mariadb
    ports:
      - "8091:80"
    networks:
      - application
networks:
    application:
        driver: bridge
